### ISSUE TITLE
Percentage circle for ReactJS?

### ISSUE THREAD

**Issue by epas1117** [JackPu/react-native-percentage-circle#14]
Hi, I love the percentage circle for React Native, It works very well, good work. I was wondering If it could be possible to use it with ReactJS in the web?

**Comment by JackPu** [comment]
OK，I'll write one soon. It is easy to extend to web.

**Comment by JackPu** [comment]
@epas1117  Hello, I have publish a new component for ReactJS. You can use [ReactJS-percentage-circle](https://github.com/JackPu/reactjs-percentage-circle) now 😁💐.

**Comment by epas1117** [comment]
Thx, I'll use it soon. I bet that to a lot of people will be useful.
