### ISSUE TITLE
not work in RN 0.36+

### ISSUE THREAD

**Issue by PeterRock** [JackPu/react-native-percentage-circle#3]
This is the reason
>  Fix unconstraint sizing in main axis [0a9b6be](https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27)

So, the percentage circle cannot display correctly.

Solution:
remove ` flex: 1,` line: 17 in file `index.js`
can make it work. but I don't test it in RN 0.36-

**Comment by JackPu** [comment]
@PeterRock  I am so sorry about replying your issue  that I had a vacation in Japan last few days. I'll test it in new RN version soon .Thanks so much.

**Comment by JackPu** [comment]
@PeterRock  Hello, I publish an new version of this component.It fixed your problems and I test it under 3.7. Thanks for your suggestions.
