### ISSUE TITLE
ios显示少于50%的样式会出现问题，我这样的写法有问题吗？

### ISSUE THREAD

**Issue by molala123** [JackPu/react-native-percentage-circle#31]
![2aa96545-4eb7-4a37-bdb3-f2c3e693e30e](https://user-images.githubusercontent.com/26194684/34857233-8fc2ad90-f784-11e7-9fc2-6adcf1f6b2dd.png)

![e1c51dd2-872f-48ca-91ff-77fbe5f5e02c](https://user-images.githubusercontent.com/26194684/34857245-9df44e28-f784-11e7-86f7-a64256c91f92.png)
![8cddd133-572b-4589-a185-d09eeab09e02](https://user-images.githubusercontent.com/26194684/34857249-a6b64958-f784-11e7-80b5-383f1d979a9f.png)

**Comment by bianbiandashen** [comment]
i have solved the issue,you need change these codes:

#line 11
import Platform

#line 96
// rightTransformerDegree = '0deg'; // leftTransformerDegree = -(50-percent) * 3.6 + 'deg';

if (Platform.OS == 'ios') { leftTransformerDegree = '0deg'; rightTransformerDegree = percent * 3.6 + 'deg'; }else{ leftTransformerDegree = '0deg'; rightTransformerDegree = -(50-percent) * 3.6 + 'deg'; }

#line 157
//backgroundColor: this.props.percent < 50 ? this.props.bgcolor : this.props.color,

backgroundColor: Platform.OS == 'ios' ? this.props.color : this.props.percent < 50 ? this.props.bgcolor : this.props.color,

line number maybe is wrong，just search the code :)

**Comment by JackPu** [comment]
@molala123  The bug has been fixed now. Just update it.

**Comment by linweiwei123** [comment]
@bianbiandashen It works for me！
