### ISSUE TITLE
当 percent  小于 50 时，在android上显示会有Bug

### ISSUE THREAD

**Issue by AnyGong** [JackPu/react-native-percentage-circle#5]
当 percent  小于 50 时，在android上显示会有Bug,是不支持android吗？
http://chuantu.biz/t5/44/1481040290x1960012110.png

**Comment by JackPu** [comment]
嗯，前段时间培训，没能及时回复，您能告诉我你的设备和andorid系统的版本号么？

**Comment by areiterer** [comment]
I also have this problem - you can reproduce it with the Android AVD for Nexus 6 with Android 6 (API Level 23)

**Comment by areiterer** [comment]
I created a pull request ( #10 ) for this.

**Comment by JackPu** [comment]
@AnyGong  已经修复了。

**Comment by areiterer** [comment]
I tested it with Version 1.0.6 -> It's working on my side.
