### ISSUE TITLE
可以添加在进度条内不止显示百分比，还可以显示其他信息么，效果如图

### ISSUE THREAD

**Issue by Swordce** [JackPu/react-native-percentage-circle#6]
![image](https://cloud.githubusercontent.com/assets/16829238/21168176/00277a44-c1ed-11e6-99d5-0056737ca2c7.png)

**Comment by JackPu** [comment]
@Swordce  不错哦，你这个想法（前段时间培训没能及时回复，这个我会更新后通知你） 💐

**Comment by JackPu** [comment]
@Swordce  最新版本的 1.0.3支持自定义子组件 

![image](https://cloud.githubusercontent.com/assets/4744967/21960842/8371af06-db32-11e6-8c56-0faaacad3275.png)
 
demo里面有写法
