### ISSUE TITLE
Make inside color of the circle configurable

### ISSUE THREAD

**Issue by areiterer** [JackPu/react-native-percentage-circle#7]
Hi, 

when I tried this component, I noticed that you can't use it on dark backgrounds because the inside of the circle is always white.

My suggestion would be to make this color also configurable via props, like the other ones.
Am I allowed to change this and create a PR for that?

**Comment by JackPu** [comment]
Of course, you can do that. All your contributions and suggestions are welcome 😄😄😄

**Comment by areiterer** [comment]
Added pull request #9

**Comment by areiterer** [comment]
Thank you :)

**Comment by areiterer** [comment]
Thank you!
